set(PROJ4_FOUND 1)
set(PROJ4_INCLUDE_DIRS /usr/include)
set(PROJ4_LIBRARIES proj)
if(\${LIB_SUFFIX} MATCHES 64)
set(PROJ4_LIBRARY_DIRS /usr/lib64)
else()
set(PROJ4_LIBRARY_DIRS /usr/lib)
endif()
set(PROJ4_BINARY_DIRS /usr/bin)
set(PROJ4_VERSION !PROJ_VERSION!)
message(STATUS "Found PROJ4: version \${PROJ4_VERSION}")
