#!/bin/bash

################################################################################

main() {
  if [[ $# -lt 2 ]] ; then
    echo "Usage: oval-dictionary-fetch {data-dir} {provider} {version}..."
    echo ""
    echo "Available providers:"
    echo ""
    echo "  alpine"
    echo "  amazon"
    echo "  debian"
    echo "  oracle"
    echo "  redhat"
    echo "  suse"
    echo "  ubuntu"
    echo "  all"
    echo ""
    exit 0
  fi

  local dir="$1"
  local provider="$2"

  if [[ ! -e "$dir" || ! -d "$dir" ]] ; then
    echo "Wrong path to data directory"
    exit 1
  fi

  shift 2

  if [[ "$provider" == "all" ]] ; then
    fetchAll "$dir"
  else
    fetch "$dir" "$provider" "$@"
  fi
}

fetchAll() {
  local dir="$1"

  fetch "$dir" redhat 6 7
  fetch "$dir" ubuntu 12 14 16 18
  fetch "$dir" alpine 3.3 3.4 3.5 3.6 3.7
  fetch "$dir" suse 15.0
  fetch "$dir" debian 7 8 9
  fetch "$dir" oracle
  fetch "$dir" amazon
}

fetch() {
  local dir="$1"
  local provider="$2"

  shift 2

  case $provider in
    "suse") oval-dictionary "fetch-suse" -opensuse-leap -dbpath "$dir/oval.sqlite3" $@ ;;
    *)      oval-dictionary "fetch-$provider" -dbpath "$dir/oval.sqlite3" $@ ;;
  esac

  [[ $? -ne 0 ]] && exit 1
}

################################################################################

main "$@"
