#!/bin/bash

################################################################################

main() {
  if [[ $# -ne 2 ]] ; then
    echo "Usage: ./cve-dictionary-fetch {data-dir} {year}"
    exit 0
  fi

  local dir="$1"
  local year="$2"

  if [[ ! -e "$dir" || ! -d "$dir" ]] ; then
    echo "Wrong path to data directory"
    exit 1
  fi

  fetch "$dir" "$year"
}

fetch() {
  local dir="$1"
  local year="$2"

  if [[ "$year" == "all" ]] ; then
    year=$(getAllYears)
  elif [[ "$year" == "current" ]] ; then
    year=$(date +%Y)
  fi

  go-cve-dictionary fetchnvd -dbpath "$dir/cve.sqlite3" -years $year

  [[ $? -ne 0 ]] && exit 1

  go-cve-dictionary fetchjvn -dbpath "$dir/cve.sqlite3" -years $year

  [[ $? -ne 0 ]] && exit 1
}

getAllYears() {
  seq 2002 $(date +%Y) | tr '\n' ' ' | sed 's/ $//'
}

################################################################################

main "$@"
