#!/bin/sh

# Quit out if anything fails.
set -e

# Clean out patent-or-otherwise-encumbered code.
# MDC-2: 4,908,861 13/03/2007 - expired, we do not remove it but do not enable it anyway
# IDEA:  5,214,703 07/01/2012 - expired, we do not remove it anymore
# RC5:   5,724,428 01/11/2015
# EC:    ????????? ??/??/2020
# SRP:   ????????? ??/??/20??

# Remove assembler portions of IDEA, MDC2, and RC5.
(find crypto/rc5/asm -type f | xargs -r rm -fv)

# RC5, EC, SRP.
for a in rc5 ec ecdh ecdsa srp; do
  for c in `find crypto/$a -name "*.c" -a \! -name "*test*" -type f` ; do
	echo Destroying $c
	> $c
  done
done

for c in `find crypto/evp -name "*_rc5.c" -o -name "*_ecdsa.c"`; do
	echo Destroying $c
	> $c
done

for c in `find crypto/bn -name "*gf2m.c"`; do
	echo Destroying $c
	> $c
done

for h in `find crypto ssl apps test -name "*.h"` ; do
	echo Removing RC5, SRP and EC references from $h
	cat $h | \
	awk    'BEGIN {ech=1;} \
		/^#[ \t]*ifndef.*NO_SRP/ {ech--; next;} \
		/^#[ \t]*ifndef.*NO_RC5/ {ech--; next;} \
		/^#[ \t]*ifndef.*NO_EC/ {ech--; next;} \
		/^#[ \t]*ifndef.*NO_ECDH/ {ech--; next;} \
		/^#[ \t]*ifndef.*NO_ECDSA/ {ech--; next;} \
                /^#[ \t]*if/ {if(ech < 1) ech--;} \
		{if(ech>0) {;print $0};} \
		/^#[ \t]*endif/ {if(ech < 1) ech++;}' > $h.hobbled && \
	mv $h.hobbled $h
done

# Make the makefiles happy.
touch crypto/rc5/asm/rc5-586.pl
