################################################################################

%global crc_check pushd ../SOURCES ; sha512sum -c %{SOURCE100} ; popd

################################################################################

%global rpmmacrodir /usr/lib/rpm/macros.d

################################################################################

Summary:        Small build system with a focus on speed
Name:           ninja-build
Version:        1.11.1
Release:        0%{?dist}
License:        ASL 2.0
Group:          Development/Tools
URL:            https://ninja-build.org

Source0:        https://github.com/ninja-build/ninja/archive/v%{version}/ninja-%{version}.tar.gz
Source1:        macros.ninja

Source100:      checksum.sha512

BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  gcc-c++ asciidoc

%if 0%{?rhel} <= 7
BuildRequires:  cmake3
%else
BuildRequires:  cmake
%endif

Provides:       %{name} = %{version}-%{release}

################################################################################

%description
Ninja is a small build system with a focus on speed. It differs from other
build systems in two major respects: it is designed to have its input files
generated by a higher-level build system, and it is designed to run builds as
fast as possible.

################################################################################

%prep
%{crc_check}

%setup -qn ninja-%{version}

%build
%if 0%{?rhel} <= 7
cmake3 -B build
cmake3 --build build
%else
cmake -B build
cmake --build build
%endif

%install
rm -rf %{buildroot}

install -dm 0755 %{buildroot}%{_bindir}
install -dm 0755 %{buildroot}%{rpmmacrodir}

install -pm 0755 build/ninja %{buildroot}%{_bindir}/ninja
install -pm 0644 %{SOURCE1} %{buildroot}%{rpmmacrodir}/macros.ninja

ln -sf ninja %{buildroot}%{_bindir}/%{name}

%clean
rm -rf %{buildroot}

################################################################################

%files
%defattr(-,root,root,-)
%doc README.md COPYING
%{_bindir}/ninja
%{_bindir}/ninja-build
%{rpmmacrodir}/macros.ninja

################################################################################

%changelog
* Fri Dec 09 2022 Anton Novojilov <andy@essentialkaos.com> - 1.11.1-0
- Initial build
