name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Perfecto docker image
        uses: docker://ghcr.io/essentialkaos/perfecto:centos7
        with:
          args: --version

      - name: Install perfecto-docker
        run: |
          wget https://kaos.sh/perfecto/perfecto-docker
          chmod +x perfecto-docker

      - name: Run Perfecto check
        env:
          IMAGE: ghcr.io/essentialkaos/perfecto:centos7
        run: ./perfecto-docker -A PF20 $(git diff --name-status origin/master | tr '\t' ' ' | grep -Ev '(^D| test/)' | grep '\.spec' | rev | cut -f1 -d' ' | rev | sort)

  Bibop:
    name: Bibop
    runs-on: ubuntu-latest

    steps:
      - name: Setup PATH
        run: |
          echo "${{ github.workspace }}" >> "$GITHUB_PATH"

      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install bibop and bibop-massive
        run: |
          wget https://apps.kaos.st/bibop/latest/linux/x86_64/bibop
          wget https://kaos.sh/bibop/scripts/bibop-massive
          chmod +x bibop bibop-massive
          bibop -v
          bibop-massive -v

      - name: Run bibop recipes validation
        env:
          TERM: xterm-256color
        run: bibop-massive -V tests
